# .codecov.yml
coverage:
  status:
    project:
      default:
        target: 80%          # Target coverage percentage
        threshold: 1%        # Allow 1% decrease
    patch:
      default:
        target: 80%          # New code should have 80% coverage

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/"              # Ignore test files from coverage
  - "setup.py"
  - "docs/"