name: Build and Deploy Documentation

on:
  push:
    branches: [ main, master ]
    paths:
      - 'dialogue-guardian/docs/**'
      - 'dialogue-guardian/src/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'dialogue-guardian/docs/**'
      - 'dialogue-guardian/src/**'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd dialogue-guardian
        pip install -e .
        pip install -r dev-requirements.txt
    
    - name: Build documentation
      run: |
        cd dialogue-guardian/docs
        make html
    
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: dialogue-guardian/docs/_build/html/
    
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dialogue-guardian/docs/_build/html