name: Manual Test

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: true
        default: 'hello'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test manual trigger
      run: |
        echo "Manual workflow triggered!"
        echo "Input: ${{ github.event.inputs.test_input }}"