name: Create Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        persist-credentials: true
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version build
    
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --local url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
    
    - name: Bump version
      id: bump
      working-directory: dialogue-guardian
      run: |
        # Create .bumpversion.cfg if it doesn't exist
        if [ ! -f .bumpversion.cfg ]; then
          cat > .bumpversion.cfg << 'EOF'
        [bumpversion]
        current_version = 1.1.0
        commit = True
        tag = True
        tag_name = v{new_version}
        
        [bumpversion:file:setup.py]
        search = version="{current_version}"
        replace = version="{new_version}"
        
        [bumpversion:file:pyproject.toml]
        search = version = "{current_version}"
        replace = version = "{new_version}"
        
        [bumpversion:file:src/guardian/__init__.py]
        search = __version__ = "{current_version}"
        replace = __version__ = "{new_version}"
        EOF
        fi
        
        # Bump version
        bump2version ${{ github.event.inputs.version_type }}
    
    - name: Get new version
      id: get_version
      working-directory: dialogue-guardian
      run: |
        # Extract version using Python to avoid shell parsing issues
        NEW_VERSION=$(python -c "
        import configparser
        config = configparser.ConfigParser()
        config.read('.bumpversion.cfg')
        print(config['bumpversion']['current_version'])
        ")
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
    
    - name: Build package
      working-directory: dialogue-guardian
      run: |
        python -m build
    
    - name: Generate changelog
      working-directory: dialogue-guardian
      run: |
        # Simple changelog generation
        echo "## Version $NEW_VERSION" > CHANGELOG_ENTRY.md
        echo "" >> CHANGELOG_ENTRY.md
        echo "### Changes" >> CHANGELOG_ENTRY.md
        git log --oneline --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> CHANGELOG_ENTRY.md || echo "- Initial release" >> CHANGELOG_ENTRY.md
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.NEW_VERSION }}
        name: Release v${{ env.NEW_VERSION }}
        body_path: dialogue-guardian/CHANGELOG_ENTRY.md
        draft: false
        prerelease: ${{ github.event.inputs.prerelease }}
        files: dialogue-guardian/dist/*
        make_latest: true
        generate_release_notes: true